apiVersion: apps/v1
kind: Deployment

metadata:
  name: renuja-devops-app
  namespace: renuja-devops

spec:
  replicas: 2

  selector:
    matchLabels:
      app: renuja-devops-app

  template:
    metadata:
      labels:
        app: renuja-devops-app

    spec:
      serviceAccountName: renuja-devops-app-sa
      containers:
        - name: renuja-devops-app
          image: 486940689963.dkr.ecr.us-east-1.amazonaws.com/renuja-devops-app:placeholder
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: renuja-devops-config

          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true

          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"

      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: renuja-devops-secrets
