apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: renuja-devops-secrets
  namespace: renuja-devops

spec:
  provider: aws

  parameters:
    region: "us-east-1"
    usePodIdentity: "true"

    objects: |
      - objectName: "renuja-devops/app-secret"
        objectType: "secretsmanager"
        objectAlias: "APP_SECRET"
